### PR TITLE
User selectable filtering

### LINKED ISSUE #9: Add threshold for low-numbered outliers
Following discussion with @milanwiedemann and @brianmackenna  on 2021-10-04,  there are some "outliers" with n=1 prescribed items with mean≈0 ∴ high z-score which may be of low importance (e.g. cod liver oil) or those where even 1 prescription is of extreme importance (e.g. withdrawn from sale drugs).

Options discussed:
- Leave as-is, let end users feed back
- Filter all low-N outliers
- Develop heuristic for non-uniform filtering
- Selectable low-N suppression in frontend

### PR DESCRIPTION
**Pull request by Jongmassey**
uses styles from #40 and resolves #9 

Allows users to choose how many outliers displayed in each table (up to max created in database build)
Allows users to hide low-numbered (currently configured as chemical items <5) outliers

### CODE REVIEW

**Comment by Jongmassey** [comment]
@tomodwyer I've added classes to the main rows of both the high- and low- outlier tables which indicate the row number and whether it's a low-count outlier for purposes of filtering. Can I hand the frontend dev over to you?

**Comment by Jongmassey** [comment]
Feature requests from @brianmackenna :
* Reduce number of lines of introductory text displayed, hiding rest behind a collapsed element (or similar, [example](https://jsfiddle.net/g4q5vp2f/1/) )

**Comment by tomodwyer** [comment]
@Jongmassey added a collapsing element to the template.

**Comment by Jongmassey** [comment]
looks ruddy lovely. Will do a more thorough review this afternoon and should merge with no problems.

**Comment by tomodwyer** [comment]
Grand 👍  you'll need to re-run the notebook to create the HTML as I've only been updating the templates.

**Pull request closed without merging**
