### PR TITLE
Hierarchical Table of Contents

### PR DESCRIPTION
**Pull request by Jongmassey**
HTML Landing page for reports with hierarchical directory structure

### CODE REVIEW

**Comment by Jongmassey** [comment]
[Index Page](https://raw.githack.com/ebmdatalab/outliers/hierarchical_toc/data/index.html) for testing

**Comment by brianmackenna** [comment]
Each "chapter" in the hierarchy only includes a single member. Or am I doing something wrong?

image

**Comment by Jongmassey** [comment]
No, I've not generated the full batch of reports - they're just limited to 100 of each and one down each part of the tree. Shall I run a full batch?

**Comment by brianmackenna** [comment]
That makes sense - I think ok to wait to run all organisations if more PRs need to be merged first!

The code is beyond me but the UI is intuitive and works well. I think our target audience will be ok with it.

**Review by brianmackenna — COMMENTED** [review]
The code is beyond me but the UI is intuitive and works well. I think our target audience will be ok with it.

**Review by alexwalkerepi — APPROVED** [review]
I also think this looks great from a user perspective, and while I have a high level understanding of what's happening I think a more in depth code review would be good at some point.

**Pull request merged**
